## Learn NumPy : NumPy 50 exercises and solution

#### 1. Importing the required library

In [5]:

import numpy as np
print(f'The numpy version installed is {np.__version__}')

import pandas as pd
print(f'The pandas version installed is {pd.__version__}')


The numpy version installed is 1.26.2
The pandas version installed is 2.1.4


#### 2. How to create a 1D array

In [7]:

my_list = [1, 2, 3, 5]
my_array = np.array(my_list)
print(my_array)
print(type(my_array))


[1 2 3 5]
<class 'numpy.ndarray'>


#### 3. How to create a boolean array

In [8]:

my_list_tf = [True, False, True, False]
my_array_tf = np.array(my_list_tf, dtype=bool)
print(my_array_tf)
print(type(my_array_tf))


[ True False  True False]
<class 'numpy.ndarray'>


Other solution could be:

In [10]:
np.full((12), True, dtype=bool).reshape(4,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 4. How to extract items that satisfy a given condition from 1D array?

In [50]:

print(f'Original array:\n {my_array}')

my_array_e = my_array[my_array % 2 == 0]            
print(f'\nEven numbers:\n {my_array_e}')

my_array_o = my_array[my_array % 2 == 1]            
print(f'\nOdds numbers:\n {my_array_o}')


Original array:
 [1 2 3 5]

Even numbers:
 [2]

Odds numbers:
 [1 3 5]


#### 5. How to replace items that satisfy a condition with another value in numpy array?

In [51]:

my_array_e2 = my_array_e[my_array_e % 2 == 0] = 100
print(f'When an even number is found, it is replaced by 100:\n {my_array_e}')

my_array_o2 = my_array_o[my_array_o % 2 == 1] = -2
print(f'\nWhen an odds number is found, it is replaced by -2:\n {my_array_o}')



When an even number is found, it is replaced by 100:
 [100]

When an odds number is found, it is replaced by 2:
 [-2 -2 -2]


An easier solution could be

In [44]:
arr = np.arange(10)

arr[arr%2 == 1] = -100
arr

array([   0, -100,    2, -100,    4, -100,    6, -100,    8, -100])

#### 6. How to replace items that satisfy a condition without affecting the original array?

In [52]:

my_list = [1, 2, 3, 5]
my_array = np.array(my_list)

my_array_e3 = my_array.copy()

my_array_e3 = my_array_e3[my_array_e3 % 2 == 0]             # even numbers
print(f'Original: {my_array}')
print(f'Modified: {my_array_e3}')



Original: [1 2 3 5]
Modified: [2]


#### 7. How to reshape an array?
Where (rows, cols)

In [60]:

c = my_array.reshape(2,2)                    
c1 = my_array.reshape(len(my_array),-1)      # -1 means that the cols are selected automatically

print(f'First array:\n {c}')
print(f'\nReshaped array:\n {c1}')


First array:
 [[1 2]
 [3 5]]

Reshaped array:
 [[1]
 [2]
 [3]
 [5]]


#### 8. How to stack two arrays vertically?

In [54]:
# Using (n, -1)

d = c1.copy() + 1
e = d.reshape(2,-1)
print(e)

f = np.vstack([c, e])
f

[[2 3]
 [4 6]]


array([[1, 2],
       [3, 5],
       [2, 3],
       [4, 6]])

#### 9. How to stack two arrays horizontally?

In [61]:

c2 = c1 + 1
c2 = c2.reshape(1,len(c2))
print(c2)

c1 = c1.reshape(1,len(c1))
print(c1)

g = np.hstack([c2, c1])
g

[[2 3 4 6]]
[[1 2 3 5]]


array([[2, 3, 4, 6, 1, 2, 3, 5]])

#### 10. How to generate custom sequences in numpy without hardcoding?

In [68]:

h = np.arange(1,4)
h1 = np.r_[np.repeat(h, 2)]
print(h1)

h2 = np.r_[np.tile(h, 2)]
print(h2)


[1 1 2 2 3 3]
[1 2 3 1 2 3]


#### 11. How to get the common items between two python numpy arrays?

In [69]:

print(f'\nOriginals: \n{my_array} and {h2}')

i = np.intersect1d(my_array, h2)
print(f'\n The common items are: \n{i}')



Originals: 
[1 2 3 5] and [1 2 3 1 2 3]

 The common items are: 
[1 2 3]


#### 12. How to remove from one array those items that exist in another?

In [70]:

j = np.setdiff1d(my_array, h2)
j


array([5])

#### 13. How to get the positions where elements of two arrays match?

In [71]:

k = np.where(h1 == h2)
k


(array([0, 5]),)

#### 14. How to extract all numbers between a given range from a numpy array?
We can put filters inside an array using the input() function

In [72]:

print(h2)
h3 = h2[(h2 >= int(input('Enter a number between 0 and 5: ')))]           
h3


[1 2 3 1 2 3]


array([1, 2, 3, 1, 2, 3])

#### 15. How to make a python function that handles scalars to work on numpy arrays?

In [73]:

print(my_array)

def my_function(x):
    if isinstance(x, (int, float)):  # Check if x is a scalar
        # Handle the scalar case
        result = x * 2  # Replace with your scalar operation
    else:
        result = x * 2  # Replace with your array operation
    return result

# Example usage
scalar = my_function(10)
print("Scalar result:", scalar)

l = my_function(my_array)
print("Array result:", l)


[1 2 3 5]
Scalar result: 20
Array result: [ 2  4  6 10]


#### 16. How to swap two columns in a 2d numpy array?

In [74]:

m = np.vstack([my_array, l])
# m.reshape(4,2)
print(f'\nOriginal: \n{m}')

m1 = m[:,[1,0,2,3]]
print(f'\nChanged: \n{m1}')

# something more general could be:
m[:, [0, 1]] = m[:, [1, 0]]
print(f'\nAlternative: \n{m}')



Original: 
[[ 1  2  3  5]
 [ 2  4  6 10]]

Changed: 
[[ 2  1  3  5]
 [ 4  2  6 10]]

Alternative: 
[[ 2  1  3  5]
 [ 4  2  6 10]]


#### 17. How to swap two rows in a 2d numpy array?

In [76]:

n = np.vstack([my_array, l, c1.reshape(1,4)+1])
print(f'\nOriginal: \n{n}')

n1 = n[[1,0,2],:]
print(f'\nChanged: \n{n1}')

n[[0, 1],:] = n[[1, 0], :]
print(f'\nAlternative: \n{n}')



Original: 
[[ 1  2  3  5]
 [ 2  4  6 10]
 [ 2  3  4  6]]

Changed: 
[[ 2  4  6 10]
 [ 1  2  3  5]
 [ 2  3  4  6]]

Alternative: 
[[ 2  4  6 10]
 [ 1  2  3  5]
 [ 2  3  4  6]]


#### 18. How to reverse the rows of a 2D array?

In [77]:

print(f'\nOriginal: \n{n}')

n2 = n[::-1]
print(f'\nChanged: \n{n2}')

n3 = n[::-1, :]
print(f'\nAlternative: \n{n3}')



Original: 
[[ 2  4  6 10]
 [ 1  2  3  5]
 [ 2  3  4  6]]

Changed: 
[[ 2  3  4  6]
 [ 1  2  3  5]
 [ 2  4  6 10]]

Alternative: 
[[ 2  3  4  6]
 [ 1  2  3  5]
 [ 2  4  6 10]]


#### 19. How to reverse the columns of a 2D array?

In [80]:

print(f'\nOriginal: \n{n3}')

n4 = n3[:, ::-1]
print(f'\nAlternative: \n{n4}')



Original: 
[[ 2  3  4  6]
 [ 1  2  3  5]
 [ 2  4  6 10]]

Alternative: 
[[ 6  4  3  2]
 [ 5  3  2  1]
 [10  6  4  2]]


#### 20. How to create a 2D array containing random floats between 5 and 10?

In [81]:

x, y = 5, 4

o = np.random.uniform(5, 10, size = (x, y))
o


array([[6.0614789 , 9.45322213, 6.53701531, 5.13672388],
       [9.77308719, 9.63267154, 9.85913296, 8.40178704],
       [7.69636218, 6.23678788, 8.97832738, 8.98179569],
       [7.82119951, 6.70914693, 5.28234409, 5.82739486],
       [6.14758361, 9.92473394, 9.19849555, 5.45567564]])

#### 21. How to print only 3 decimal places in python numpy array?

In [82]:

np.set_printoptions(3)
o


array([[6.061, 9.453, 6.537, 5.137],
       [9.773, 9.633, 9.859, 8.402],
       [7.696, 6.237, 8.978, 8.982],
       [7.821, 6.709, 5.282, 5.827],
       [6.148, 9.925, 9.198, 5.456]])

#### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [83]:

x, y = 5,5
p = np.random.uniform(0, 0.1, size = (x, y))/6
np.set_printoptions(suppress=False)
print(f'\n{p}')

np.set_printoptions(suppress=True, formatter={'float': lambda x: f'{x:.3f}'})
print(f'\n{p}')



[[0.011 0.012 0.003 0.002 0.001]
 [0.007 0.003 0.01  0.004 0.001]
 [0.007 0.017 0.002 0.014 0.008]
 [0.    0.005 0.015 0.015 0.002]
 [0.001 0.005 0.012 0.001 0.007]]

[[0.011 0.012 0.003 0.002 0.001]
 [0.007 0.003 0.010 0.004 0.001]
 [0.007 0.017 0.002 0.014 0.008]
 [0.000 0.005 0.015 0.015 0.002]
 [0.001 0.005 0.012 0.001 0.007]]


#### 23. How to limit the number of items printed in output of numpy array?

In [84]:

q = np.arange(100)
np.set_printoptions(threshold=6)
# print(f'\n{q}')
q


array([ 0,  1,  2, ..., 97, 98, 99])

#### 24. How to print the full numpy array without truncating

In [87]:

r = np.arange(100)
# np.set_printoptions(threshold=100)
r


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

Define the data types for each column (integer (int) for the first column, str for the second)

In [88]:

file_path = 'iris.csv'
delimiter = ','

dtype = object
data = np.genfromtxt(file_path, delimiter=delimiter, dtype=dtype, names=True, skip_header=0)
data


array([(b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'),
       (b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'),
       (b'3', b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'), ...,
       (b'148', b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'),
       (b'149', b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'),
       (b'150', b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica')],
      dtype=[('Id', 'O'), ('SepalLengthCm', 'O'), ('SepalWidthCm', 'O'), ('PetalLengthCm', 'O'), ('PetalWidthCm', 'O'), ('Species', 'O')])

#### 26. How to extract a particular column from 1D array of tuples?

In [89]:

data01 = np.genfromtxt(file_path, delimiter=delimiter, skip_header=1, 
                          usecols = [-1], dtype = object)
data01


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype=object)

#### 27. How to convert a 1d array of tuples to a 2d numpy array?

In [90]:

iris2D = np.genfromtxt(file_path, delimiter=delimiter, skip_header=1, dtype='float', usecols=[1,2,3])
iris2D


array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       ...,
       [6.5, 3. , 5.2],
       [6.2, 3.4, 5.4],
       [5.9, 3. , 5.1]])

#### 28. How to compute the mean, median, standard deviation of a numpy array?
If we write irisD[:,1], then it calculates all rows of column 2

In [91]:

mean2D = iris2D[:,1].mean().round(2)
median2D = np.median(iris2D[:,1]).round(2)
std2D = iris2D[:,1].std().round(2)

# we imported pandas to build a table as resume
table = pd.DataFrame({'Mean': [mean2D], 'Median': [median2D], 'Standard Deviation': [std2D]})
table


Mean  Median  Standard Deviation
0  3.05     3.0                0.43

#### 29. How to normalize an array, so the values range exactly between 0 and 1?
We must use the data normalization formula (X- Xmin) / (Xmax - Xmin)

In [92]:

irisNor = (iris2D[:,1] - np.min(iris2D[:,1])) / (np.max(iris2D[:,1]) - np.min(iris2D[:,1]))
irisNor


array([0.625, 0.417, 0.5  , ..., 0.417, 0.583, 0.417])

#### 30. How to compute the softmax score?

The softmax function is commonly used in machine learning and deep learning to compute a probability distribution over multiple classes.

It takes as input a vector of raw scores or logits and transforms them into a probability distribution where each score is converted to a probability value between 0 and 1.

The probabilities are normalized so that they sum to 1:

e^z / sum(e^z)

In [97]:

smax = np.exp(iris2D[:,1])/sum(np.exp(iris2D[:,1]))
smax.sum().round(5)


1.0

Applying as a function

In [95]:

def softmax(z):
    probability = np.exp(z) / sum(np.exp(z))
    return probability

softProb = softmax(iris2D[:,1])
print(f'The Maximum Softmax Probability: {softProb.sum().round(5)}')


The Maximum Softmax Probability: 1.0


#### 31. How to find the percentile scores of a numpy array?

In [98]:

s_array = np.genfromtxt(file_path, delimiter=delimiter, skip_header=1, dtype='float', usecols=[1])
s = np.percentile(s_array, [25, 50, 75])                    # percentile 25, 50 and 75
s


array([5.1, 5.8, 6.4])

#### 32. How to insert values at random positions in an array?

In [99]:

t_array = np.arange(10)
print(f'\nOriginal array: \n{t_array}')

t_ind = np.random.choice(t_array.size, size=3, replace=False)                   # Generate 3 random indices for insertion
print(f'\nThe indices for insertion is: \n{t_ind}')

t_values = np.random.randint(10, 20, size=3)                                    # Generate 3 random values for insertion
print(f'\nThe values for insertion: \n{t_values}')

t_array = np.insert(t_array, t_ind, t_values)                                   # Insert the values at the indices
print(f'\nArray after insertion: \n{t_array}')


Original array: 
[0 1 2 3 4 5 6 7 8 9]

The indices for insertion is: 
[7 0 8]

The values for insertion: 
[16 11 15]

Array after insertion: 
[11  0  1  2  3  4  5  6 16  7 15  8  9]


#### 33. How to find the position of missing values in numpy array?

In [101]:

iris2D_ind = np.random.choice(iris2D.size, size=50)                     # Generate 50 random indices for insertion
iris2D_values = iris2D[np.random.randint(len(iris2D), size=50),np.random.randint(3,size=50)] = np.nan    # Generate 50 random values for insertion
iris2D_array = np.insert(iris2D, iris2D_ind, iris2D_values)             # Insert the values at the indices

nan_positions = np.where(np.isnan(iris2D_array))
print(f'\nPositions which values are nulls in: \n{nan_positions}')



Positions which values are nulls in: 
(array([  0,   2,   3, ..., 489, 490, 499]),)


#### 34. How to filter a numpy array based on two or more conditions?

In [102]:

filter_iris2D = iris2D[((iris2D > 4) & (iris2D < 7)) & (iris2D != 'nan')]
filter_iris2D


array([4.9, 4.7, 4.6, ..., 6.2, 5.4, 5.9])

#### 35. How to drop rows that contain a missing value from a numpy array?

In [103]:

u = np.array([[1, 2], 
               [np.nan, 4], 
               [5, 6]])

u = u[~np.isnan(u).any(axis=1)]
u


array([[1., 2.],
       [5., 6.]])

#### 36. How to find the correlation between two columns of a numpy array?
As 27: convert a 1d array of tuples to a 2d numpy array


In [104]:

iris2D_x = np.genfromtxt(file_path, delimiter=delimiter, skip_header=1, dtype='float', usecols=[0,1,2,3])

x = np.corrcoef(iris2D_x[:,0], iris2D_x[:,1])
x[0,1]


0.7166762728538999

#### 37. How to find is a given array has any null values?

In [106]:

np.isnan(iris2D).any()


True

#### 38. How to replace all missing values with 0 in a numpy array?

In [107]:

iris2D[np.isnan(iris2D)] = 0
iris2D


array([[0. , 3.5, 0. ],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 0. ],
       ...,
       [6.5, 3. , 5.2],
       [6.2, 3.4, 5.4],
       [5.9, 3. , 0. ]])

#### 39. How to find the count of unique values in a numpay array?

In [109]:

y_list = [1, 2, 3, 5, 5, 4, 5, 3, 0, 1]
y = np.array(y_list)
np.unique(y, return_counts=True)


(array([0, 1, 2, 3, 4, 5]), array([1, 2, 1, 2, 1, 3]))

#### 40. How to convert a numerical to a categorical (text) array?
np.digitize() assigns an index to each data point based on the bin boundaries specified in bins

In [110]:
bins = np.array([0, 3, 5])                             # It specifies the bin boundaries for the numerical data
inds = np.digitize(s_array.astype('float'), bins)

labels = {1:'small', 2: 'medium', 3:'large'}
iris_cat_data = [labels[x] for x in inds]

print(inds)
print(iris_cat_data)

[3 2 2 ... 3 3 3]
['large', 'medium', 'medium', 'medium', 'large', 'large', 'medium', 'large', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'medium', 'large', 'medium', 'large', 'large', 'large', 'large', 'medium', 'medium', 'large', 'large', 'large', 'medium', 'large', 'large', 'medium', 'medium', 'large', 'large', 'medium', 'medium', 'large', 'large', 'medium', 'large', 'medium', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'medium', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'mediu

Other way of resolve it:

In [111]:

z = []
for i in s_array:
    if i < 3:
        z.append('small')
    elif i < 5:
        z.append('medium')
    else:
        z.append('large')
print(z)


['large', 'medium', 'medium', 'medium', 'large', 'large', 'medium', 'large', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'medium', 'large', 'medium', 'large', 'large', 'large', 'large', 'medium', 'medium', 'large', 'large', 'large', 'medium', 'large', 'large', 'medium', 'medium', 'large', 'large', 'medium', 'medium', 'large', 'large', 'medium', 'large', 'medium', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'medium', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'large', 'medium', 'large', 'larg

In [112]:
print(z == iris_cat_data)

True


#### 41. How to create a new column from existing columns of a numpy array?

In [52]:

iris2D_z1 = (iris2D[:,1] * 2) + iris2D[:,2]
iris2D_z = np.column_stack((iris2D, iris2D_z1))
print(iris2D_z)


[[ 5.1  3.5  1.4  8.4]
 [ 4.9  3.   0.   6. ]
 [ 4.7  3.2  1.3  7.7]
 ...
 [ 6.5  3.   5.2 11.2]
 [ 6.2  3.4  5.4 12.2]
 [ 5.9  3.   5.1 11.1]]


#### 42. How to do probabilistic sampling in numpy?

In [113]:

items = ['A', 'B', 'C', 'D', 'E']
probabilities = [0.1, 0.2, 0.3, 0.2, 0.2]                           # Define the probabilities for each item
sampled_item = np.random.choice(items, size=1, p=probabilities)     # Perform probabilistic sampling

print(f'Sampled Item: {sampled_item[0]}')


Sampled Item: C


#### 43. How to get the second largest value of an array when grouped by another array

In [114]:

diabetes_data = np.genfromtxt('diabetes.csv',
                              delimiter=',', dtype=object, usecols=[0,1,2,3,4,5,6,7,8], skip_header=1)

bloodpressure= diabetes_data[diabetes_data[:, 8]==b'1', [2]].astype('float')
np.unique(np.sort(bloodpressure))[-2]



# iris = data[data[:, 2]==b'1', [2]].astype('float')
# np.unique(np.sort(iris))[-2]

# I really try this code, but:\ 
# IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

110.0

#### 44. How to sort a 2D array by a column

In [115]:

np.argsort(iris2D[:,1])


array([ 74, 122, 120, ...,  14,  32,  15])

In [116]:

iris2D[iris2D[:,1].argsort()]


array([[0. , 0. , 4.3],
       [7.7, 0. , 6.7],
       [6.9, 0. , 0. ],
       ...,
       [5.8, 4. , 1.2],
       [5.2, 4.1, 0. ],
       [0. , 4.4, 1.5]])

#### 45. How to find the most frequent value in a numpy array?

In [117]:

# from 39.:
y_list = [1, 2, 3, 5, 5, 4, 5, 3, 0, 1]
y = np.array(y_list)
y_unique, y_count = np.unique(y, return_counts=True)
np.argmax(y_count)


5

#### 46. How to find the position of the first occurrence of a value greater than a given value?

In [118]:

np.argwhere(iris2D[:].astype(float) > 6.4)[0]


array([50,  0])

#### 47. How to replace all values greater than a given value to a given cutoff?

In [120]:

y_array = np.array([y_list], dtype=int)
a = 4
cutoff = 4**3                                       # You can set this to any value you want
y_array[y_array > a] = cutoff                       # Replace values greater than the threshold with the cutoff value

print(f'Modified Data: {y_array}')


Modified Data: [[ 1  2  3 64 64  4 64  3  0  1]]


#### 48. How to get the positions of top n values from a numpy array?
numpy.argsort to get the indices that would sort the array in descending order


In [121]:

z_list = [1, 2, 3, 5, 6, 4, 8, 11, 10, 0]
z_array = np.array(z_list)
n = 3                                                 # top n

sorted_indices = np.argsort(z_array)[::-1]
top_n_positions = sorted_indices[:n]                  # Select the first n indices to get the positions of the top n values

print(f'Data: {z_array}')
print(f'Positions of the top {n} values: {top_n_positions}')


Data: [ 1  2  3  5  6  4  8 11 10  0]
Positions of the top 3 values: [7 8 6]


#### 49. How to compute the row wise counts of all possible values in an array?

In [123]:

aa = [1, 2, 3]
bb = [1, 3, 3]
cc = [2, 1, 1]

dd = np.array([aa, bb, cc])

unique_values = np.unique(dd)                   # Get the unique values in the entire array


row_wise_counts = []
# Iterate through the rows
for row in dd:
    # Use a list comprehension to count the occurrences of each unique value in the row
    counts = [np.count_nonzero(row == value) for value in unique_values]
    row_wise_counts.append(counts)

row_wise_counts = np.array(row_wise_counts)

print(f'Original: \n{dd}')
print(f'\n Rows wise counts: \n{row_wise_counts}')

Original: 
[[1 2 3]
 [1 3 3]
 [2 1 1]]

 Rows wise counts: 
[[1 1 1]
 [1 0 2]
 [2 1 0]]


#### 50. How to convert an array_of_arrays into a flat linear 1d array?

In [125]:
# array_of_arrays = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Use numpy.ravel() to flatten the array
flat_array = dd.ravel()
print(f'First choice: \n{flat_array}')

flat_array1 = np.concatenate(row_wise_counts)
print(f'\nSecond choice: \n{flat_array1}')

First choice: 
[1 2 3 1 3 3 2 1 1]

Second choice: 
[1 1 1 1 0 2 2 1 0]
